In [26]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [27]:
data = pd.read_csv('Advertising.csv')
data.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [28]:
data.describe()

TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [29]:
x = data[['TV', 'Radio', 'Newspaper']]
y = data['Sales']

In [30]:
reg = LinearRegression()
reg.fit(x, y)

LinearRegression()

In [31]:
reg.coef_

array([ 0.04576465,  0.18853002, -0.00103749])

In [32]:
reg.intercept_

2.9388893694594085

Calculating R-squared

In [34]:
reg.score(x, y)

0.8972106381789522

### Formula  for adjusted r^2
$R^2_{adj.} = 1 - (1 - R^2)*\frac{n-1}{n-p-1}$

In [40]:
x.shape

(200, 3)

In [41]:
r2 = reg.score(x, y)

n = x.shape[0]
p = x.shape[1]

adjusted_r2 = 1 - (1-r2)* (n-1)/(n-p-1)
adjusted_r2

0.8956373316204668

### Feature Selection

In [42]:
from sklearn.feature_selection import f_regression


In [43]:
f_regression(x, y)

(array([312.14499437,  98.42158757,  10.88729908]),
 array([1.46738970e-42, 4.35496600e-19, 1.14819587e-03]))

p_values = f_regression(x, y)[1]
p_values.round(3)

### Crating a summary Table

In [49]:
reg_summary = pd.DataFrame(data = x.columns.values, columns=['Fearures'])
reg_summary

Fearures
0         TV
1      Radio
2  Newspaper

In [50]:
reg_summary['coefficient'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)
reg_summary

Fearures  coefficient  p-values
0         TV     0.045765     0.000
1      Radio     0.188530     0.000
2  Newspaper    -0.001037     0.001

### Standardization

In [52]:
from sklearn.preprocessing import StandardScaler

In [54]:
scaler = StandardScaler()

In [55]:
scaler.fit(x)

StandardScaler()

In [57]:
x_scaled = scaler.transform(x)

### Regression with scaled features

In [59]:
reg = LinearRegression()
reg.fit(x_scaled, y)

LinearRegression()

In [60]:
reg.coef_

array([ 3.91925365,  2.79206274, -0.02253861])

In [61]:
reg.intercept_

14.0225

### Creating Summary Table

In [65]:
reg_summary = pd.DataFrame([['Tv'], ['Radio'], ['Newspaper']], columns=['Fearures'])
reg_summary['Weights'] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [66]:
reg_summary

Fearures    Weights
0         Tv  14.022500
1      Radio   3.919254
2  Newspaper   2.792063

### Making Predictions with standardized coefficients(weights)

In [69]:
new_data = pd.DataFrame(data=[[230, 40, 70]], columns=['Tv', 'Radio', 'Newspaper'])
new_data

Tv  Radio  Newspaper
0  230     40         70

In [73]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

C:\Users\Aakash\anaconda3\lib\site-packages\sklearn\base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- Tv
Feature names seen at fit time, yet now missing:
- TV

  warnings.warn(message, FutureWarning)


array([[0.96868458, 1.1300743 , 1.81577092]])

In [75]:
reg.predict(new_data_scaled)

array([20.93333399])